# redis配置
redis-host: ${REDIS_HOST:39.106.12.42}
redis-port: ${REDIS_PORT:6379}
redis-password: ${REDIS_PASSWORD:root@123456}

# mysql配置
mysql-host: ${MYSQL_HOST:39.106.12.42}
mysql-port: ${MYSQL_PORT:3306}
mysql-username: ${MYSQL_USERNAME:root}
mysql-password: ${MYSQL_ROOT_PASSWORD:2W0x0y40706@}

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woj
    username: ${mysql-username}
    password: ${mysql-password}
  data:
    redis:
      host: ${redis-host}
      port: ${redis-port}
      password: ${redis-password}
      jedis:
        pool:
          min-idle: 10 #连接池中的最小空闲连接
          max-idle: 50 #连接池中的最大空闲连接
          max-active: 200 #连接池最大连接数（使用负值表示没有限制）
          max-wait: 2000 #连接池最大阻塞等待时间（使用负值表示没有限制）

server:
  port: 8088
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除字段
      logic-delete-field: isDelete
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false

springdoc:
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
  setting:
    language: zh_cn
  documents:
      group: 2.X版本
      name: 接口签名
      locations: classpath:sign/*


emailUtil:
  hostName: smtp.qq.com
  Charset: "UTF-8"
  account: 3153917921@qq.com
  password: unijbjmgvfspdddb
  name: AcKing
# spring 事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#自定义代码代码沙箱的输出地址，默认为false，使用项目目录下的questionCode作为文件的输出地址，开启后将使用指定的地址
codefile:
  judgecasepath: "D:\\Desktop\\WOJ\\NEW\\WOJ\\WOJ\\judgeCase"

